### ISSUE TITLE
Cannot write tags to m4a files

### ISSUE THREAD

**Issue by luisfl** [hexise/jaudiotagger-android#4]
Writing tags to m4a files created with MediaRecorder through a CannotReadException exception in AudioFileIO.read because of "Invalid indentifier".  Please see here for more details:

      https://stackoverflow.com/questions/72154696/mediarecorder-produces-jaudiotagger-cannotreadexception

Here is the Stack Trace:

2022-05-07 17:57:28.283 5193-5193/com.floritfoto.apps.ave E/atom: Skipped 64bit data length, now at:96716
2022-05-07 17:57:28.306 5193-5193/com.floritfoto.apps.ave E/atom: Skipped 64bit data length, now at:96716
2022-05-07 17:57:28.309 5193-5193/com.floritfoto.apps.ave E/generic: File /storage/58ED-1620/Ave/MySongs/ave_220507-175721.m4a being read
    org.jaudiotagger.audio.exceptions.NullBoxIdException: Unable to find next atom because identifier is invalid ��������
        at org.jaudiotagger.audio.mp4.atom.Mp4BoxHeader.update(Mp4BoxHeader.java:155)
        at org.jaudiotagger.audio.mp4.atom.Mp4BoxHeader.seekWithinLevel(Mp4BoxHeader.java:357)
        at org.jaudiotagger.audio.mp4.Mp4TagReader.read(Mp4TagReader.java:117)
        at org.jaudiotagger.audio.mp4.Mp4FileReader.getTag(Mp4FileReader.java:46)
        at org.jaudiotagger.audio.generic.AudioFileReader.read(AudioFileReader.java:119)
        at org.jaudiotagger.audio.AudioFileIO.readFile(AudioFileIO.java:359)
        at org.jaudiotagger.audio.AudioFileIO.read(AudioFileIO.java:196)
        at com.floritfoto.apps.ave.Register.writeID3Tags(Register.java:623)
        at com.floritfoto.apps.ave.Register.RecordSongM4A(Register.java:282)
        at com.floritfoto.apps.ave.Register.RecordSong(Register.java:265)
        at com.floritfoto.apps.ave.Register.lambda$onCreate$9$com-floritfoto-apps-ave-Register(Register.java:740)
        at com.floritfoto.apps.ave.Register$$ExternalSyntheticLambda14.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7792)
        at android.view.View.performClickInternal(View.java:7769)
        at android.view.View.access$3800(View.java:910)
        at android.view.View$PerformClick.run(View.java:30218)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by kiradanish2-boop** [comment]
https://stackoverflow.com/questions/72154696/mediarecorder-produces-jaudiotagger-cannotreadexceptioa
